# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-06 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='json',
            new_name='json_data',
        ),
    ]
