# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20171022_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(max_length=1024),
        ),
    ]
