# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171022_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
    ]
